//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dashboard
{
    using System;
    using System.Collections.Generic;
    
    public partial class CodeValue
    {
        public int CodeNamespaceId { get; set; }
        public int Value { get; set; }
        public string Description { get; set; }
        public Nullable<int> OrderBy { get; set; }
    
        public virtual CodeNamespace CodeNamespace { get; set; }
    }
}
