//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dashboard
{
    using System;
    using System.Collections.Generic;
    
    public partial class RevenueTrackerData
    {
        public string Name { get; set; }
        public Nullable<decimal> Total_Finance_PEPM_Calculated { get; set; }
        public Nullable<decimal> Total_Finance_One_Time_Calculated { get; set; }
        public Nullable<int> Month { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<System.DateTime> Contract_Date { get; set; }
        public string Projected_Assignment { get; set; }
        public Nullable<System.DateTime> Projected_Project_Start_Date { get; set; }
        public string Imp_Planned_KO { get; set; }
        public string Status_Comments { get; set; }
        public string Hold_Explanation { get; set; }
        public string Status { get; set; }
        public string PSID { get; set; }
        public int Id { get; set; }
        public int FK_RevenueTrackerData_Report { get; set; }
    
        public virtual Report Report { get; set; }
    }
}
