//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dashboard
{
    using System;
    using System.Collections.Generic;
    
    public partial class SerieEntity
    {
        public int Id { get; set; }
        public int ChartEntityId { get; set; }
        public int CategoryId { get; set; }
        public int SerieType { get; set; }
        public string SerieName { get; set; }
        public string PointsAsString { get; set; }
    
        public virtual ChartEntity ChartEntity { get; set; }
    }
}
